base: 
  name: bbc_avg
  DEVICE: cuda:0
  seed: 0
  params: 
    clip_len: 21
    dropout: 0.2
  data_root: ../data/BBC
  save_root: ../checkpoints/bbc_avg
  path: 
    feature_path:
      - ${base.data_root}/ImageNet_shot.pkl
      - ${base.data_root}/Places_shot.pkl
    scene_path: ${..data_root}/scene_annotation.pkl
    shot_path: ${..data_root}/shot_annotation.pkl
    label_path: ${..data_root}/label_dict.pkl
  model: model

finetune:
  aim_index:
  params: 
    num_workers: 12
    batch_size: 256
    lr: 1e-4
    from_epoch: 0
    total_epochs: 11
    label_percentage: 100
  load_path: ../checkpoints/selfsup_best/pretrain/epoch=10.pt
  train: 
    dataset: finetune_base
    vid_list: train_vids
  test: 
    dataset: finetune_base
    vid_list: test_vids
  optim: Adam

evaluate: 
  params: 
    num_workers: 12
    batch_size: 1024
  load_path: ${base.save_root}/${base.name}/finetune/epoch=10.pt
  test: 
    dataset: finetune_base
    vid_list: test_vids
  head: sbd
