base: 
  name: NN_lesslabel
  DEVICE: cuda:0
  seed: 0
  params: 
    clip_len: 9
    dropout: 0.1
  data_root: ../data/MovieNet
  save_root: ../checkpoints
  path: 
    feature_path:
      - ${base.data_root}/NN_shot.pkl
    split_path: ${..data_root}/movie1K.split.v1.json
    scene_path: ${..data_root}/scene_annotation.pkl
    shot_path: ${..data_root}/shot_annotation.pkl
    label_path: ${..data_root}/label_dict.pkl
  model: model_nn

finetune:
  params: 
    num_workers: 12
    batch_size: 1024
    lr: 1e-5
    from_epoch: 0
    total_epochs: 11
    label_percentage: 100
  train: 
    dataset: finetune_base
    vid_list: train_vids
  test: 
    dataset: finetune_base
    vid_list: test_vids
  optim: Adam
