base: 
  name: selfsup_bbc
  DEVICE: cuda:0
  seed: 0
  params: 
    clip_len: 21
    dropout: 0.2
  data_root: ../data/BBC
  save_root: ../checkpoints
  path: 
    feature_path:
      - ${base.data_root}/ImageNet_shot.pkl
      - ${base.data_root}/Places_shot.pkl
    scene_path: ${..data_root}/scene_annotation.pkl
    shot_path: ${..data_root}/shot_annotation.pkl
    label_path: ${..data_root}/label_dict.pkl
  model: model

evaluate: 
  params: 
    num_workers: 12
    batch_size: 1024
  load_path: ${base.save_root}/${base.name}/finetune/epoch=10.pt
  test: 
    dataset: finetune_base
    vid_list: test_vids
  head: sbd
