DEVICE: cuda:0
batch_size: 64
num_workers: 8
model: ImageNet
data_root: /root/project/data/BBC
save_path: ${data_root}/ImageNet_BBC_shot.h5
keyframes_root: ${data_root}/keyframes_from_240P
dataset: imagenet