DEVICE: cuda:0
batch_size: 64
num_workers: 8
model: ImageNet
data_root: /root/project/data/MovieNet
save_path: ${data_root}/ImageNet_shot.h5
keyframes_root: ${data_root}/keyframes_from_240P
split_path: ${data_root}/movie1K.split.v1.json
dataset: imagenet